"""Add tickets purchased to Participant model

Revision ID: 0225f76c49dc
Revises: da222b89a20b
Create Date: 2024-01-22 20:44:45.033036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0225f76c49dc'
down_revision = 'da222b89a20b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_tickets_purchased', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_column('num_tickets_purchased')

    # ### end Alembic commands ###
