"""Add ticketing fields to Event

Revision ID: da222b89a20b
Revises: 
Create Date: 2024-01-22 20:07:34.799978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da222b89a20b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tickets_available', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ticket_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('ticket_price')
        batch_op.drop_column('tickets_available')

    # ### end Alembic commands ###
